### ISSUE TITLE
Fix SuperSelects

### ISSUE THREAD

**Issue by bradenhutch** [BYU-ODH/yvideo#69]
Many superselects died including (but probably not limited to) the one in the edit collections modal and the content edit metadata modal.

**Comment by dro248** [comment]
The issue is that Bootstrap modals are made to steal focus by default. This makes things difficult when attempting to create modal child elements of type input.

This line fixes the problem.
 [https://github.com/BYU-ODH/EditorWidgets/blob/676a967a769480a9782eb7dcc550001dff81d6f3/js/SuperSelect.js#L145](url)
